### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by lyj157175** [ZhengkunTian/OpenTransformer#13]
请问这个项目使用的Mandarin Chinese进行训练的嘛？

**Comment by ZhengkunTian** [comment]
用什么语言都能训练，例子是aishell的，中文数据

**Comment by lyj157175** [comment]
好的，谢谢！我看您的代码写的非常清楚，准备好好研究一下。我刚准备做语音识别项目不是太明白。
麻烦再问一下哈：
1. 您是说模型训练用的aishell数据集是嘛？还是测试用的这个数据集
2.比如我下载了其它中或英文数据集，数据处理是一样嘛，处理成您的readme的样子嘛（因为我可能中英数据集都会用到）
3. 相对于seq2seq+attention（LAS）模型的话数据的输入格式是不是不一样呀



在 2020-07-28 17:57:47，"ZhengkunTian" <notifications@github.com> 写道：

用什么语言都能训练，例子是aishell的，中文数据

**Comment by ZhengkunTian** [comment]
1、Aishell里面包含训练集和测试集！
2、对于英文和中文处理方式有些不同，中文使用汉字作为建模单元，因为可以使用字母或者wordpiece来建模
3、没有区别。



发件人: 韩小信<mailto:notifications@github.com>
发送时间: 2020年7月28日 18:36
收件人: ZhengkunTian/OpenTransformer<mailto:OpenTransformer@noreply.github.com>
抄送: ZhengkunTian<mailto:zhengkuncasia@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [ZhengkunTian/OpenTransformer] 数据集 (#13)

好的，谢谢！我看您的代码写的非常清楚，准备好好研究一下。我刚准备做语音识别项目不是太明白。
麻烦再问一下哈：
1. 您是说模型训练用的aishell数据集是嘛？还是测试用的这个数据集
2.比如我下载了其它中或英文数据集，数据处理是一样嘛，处理成您的readme的样子嘛（因为我可能中英数据集都会用到）
3. 相对于seq2seq+attention（LAS）模型的话数据的输入格式是不是不一样呀



在 2020-07-28 17:57:47，"ZhengkunTian" <notifications@github.com> 写道：

用什么语言都能训练，例子是aishell的，中文数据

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by lyj157175** [comment]
好的，非常感谢！




在2020年07月28日 19:19，ZhengkunTian 写道：

1、Aishell里面包含训练集和测试集！
2、对于英文和中文处理方式有些不同，中文使用汉字作为建模单元，因为可以使用字母或者wordpiece来建模
3、没有区别。



发件人: 韩小信<mailto:notifications@github.com>
发送时间: 2020年7月28日 18:36
收件人: ZhengkunTian/OpenTransformer<mailto:OpenTransformer@noreply.github.com>
抄送: ZhengkunTian<mailto:zhengkuncasia@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [ZhengkunTian/OpenTransformer] 数据集 (#13)

好的，谢谢！我看您的代码写的非常清楚，准备好好研究一下。我刚准备做语音识别项目不是太明白。
麻烦再问一下哈：
1. 您是说模型训练用的aishell数据集是嘛？还是测试用的这个数据集
2.比如我下载了其它中或英文数据集，数据处理是一样嘛，处理成您的readme的样子嘛（因为我可能中英数据集都会用到）
3. 相对于seq2seq+attention（LAS）模型的话数据的输入格式是不是不一样呀



在 2020-07-28 17:57:47，"ZhengkunTian" <notifications@github.com> 写道：

用什么语言都能训练，例子是aishell的，中文数据

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
